# Generated by Django 3.2.9 on 2022-02-10 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='logoimages')),
                ('title', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('experience', models.CharField(max_length=120)),
                ('eligibility', models.CharField(max_length=120)),
                ('notice_period', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
