# Generated by Django 3.2.9 on 2022-02-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('experience', models.CharField(max_length=120)),
                ('eligibility', models.CharField(max_length=120)),
                ('notice_period', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
    ]
