# Generated by Django 3.2.9 on 2022-02-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.job'),
        ),
    ]
