# Generated by Django 3.2.9 on 2022-02-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='item',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
