# Generated by Django 3.2.9 on 2022-02-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220208_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='title',
            new_name='jo',
        ),
    ]
