# Generated by Django 3.2.9 on 2022-02-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_title_application_jo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='jo',
            new_name='title',
        ),
    ]
