# Generated by Django 3.2.9 on 2022-02-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_jo_application_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='title',
            new_name='job_name',
        ),
    ]
